### ISSUE TITLE
feat: allow missing CC or CXX when detecting available targets

### ISSUE THREAD

**Issue by cocoa-xu** [cocoa-xu/cc_precompiler#5]
There is no need to require the presence of both `CC` and `CXX` for projects that only uses one of them. 

For example, [akash-akya/vix](https://github.com/akash-akya/vix/blob/master/.github/workflows/precompile.yaml#L22-L23) only uses `gcc` but they had to install `g++` because of this requirement.

```yaml
      - name: Install Dependencies
        run: |
          sudo apt-get update
          # we don't need g++ compiler but we `cc_precompiler` looks for
          # g++ executable to detect the target
          sudo apt-get install -y gcc make curl tar \
            gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
```

I think I can add an `allow_missing_compiler` option, e.g.,

```elixir
def project do
[ 
  # ...
  cc_precompiler: [
    # optional config key
    #   true - the corresponding target will be available as long as we can detect either `CC` or `CXX`
    #   false  - both `CC` and `CXX` should be present on the system
    # defaults to `false`
    allow_missing_compiler: false,
    # ...
  ],
  # ...
]
end
```
